config/routes.rb
Rails.application.routes.draw do
  get 'characters/index'

  resources :characters do
    resources :skills
  end
  
  root 'characters#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
    self.table_name = "Characters"
end

app/models/condition.rb
class Condition < ApplicationRecord
    self.table_name = "Conditions"
end

app/models/entity.rb
class Entity < ApplicationRecord
    self.table_name = "Entities"
    belongs_to :race, foreign_key: "RaceId"
    belongs_to :condition, foreign_key: "ConditionId"
    belongs_to :statistic, foreign_key: "StatisticsId"

    has_many :entity_skill, foreign_key: "EntityId"
    has_many :skill, through: :entity_skill, foreign_key: "EntityId"
end

app/models/entity_skill.rb
class EntitySkill < ApplicationRecord
    self.table_name = "EntitySkills"
    belongs_to :entity, primary_key: "Id", foreign_key: "EntityId"
    belongs_to :skill, primary_key: "Id", foreign_key: "SkillId"
end

app/models/npc.rb
class Npc < ApplicationRecord
    self.table_name = "Npcs"    
end

app/models/race.rb
class Race < ApplicationRecord
    self.table_name = "Races"
end

app/models/skill.rb
class Skill < ApplicationRecord
    self.table_name = "Skills"    
    
    has_many :entity_skill, foreign_key: "EntityId"
    has_many :entity, through: :entity_skill, foreign_key: "EntityId"
end

app/models/statistic.rb
class Statistic < ApplicationRecord
    self.table_name = "Statistics"
end

app/models/user.rb
class User < ApplicationRecord
    self.table_name = "Users"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  def index
    @characters = Entity.joins(:race).all
  end
  def show
    @character = Entity.find(params[:id])
  end
  def new
  end
  def create
    @race = Race.where(["Name = ?", params[:character][:race]]).first

    params.permit!
    @statistics = Statistic.new(:Strength => params[:character][:strength],
                                :Dexterity => params[:character][:dexterity],
                                :Inteligence => params[:character][:inteligence],
                                :Wisdom => params[:character][:wisdom],
                                :Luck => params[:character][:luck],
                                :Charisma => params[:character][:charisma])
    
    @statistics.save                          
                                
    @condition = Condition.new(:Health => (params[:character][:strength].to_i * 2),
                                  :MaxHealth => (params[:character][:strength].to_i * 2),
                                  :Mana => (params[:character][:inteligence].to_i * 2),
                                  :MaxMana => (params[:character][:inteligence].to_i * 2),
                                  :Experience => 0,
                                  :MaxExperience => 1000)
    
    @condition.save
                                  
    @entity = Entity.new(:Name => params[:character][:name],
                            :Age => params[:character][:age],
                            :Level => 1,
                            :Story => params[:character][:story],
                            :Quote => params[:character][:quote],
                            :Sex => params[:character][:sex],
                            :ConditionId => @condition.id,
                            :RaceId => @race.id,
                            :StatisticsId => @statistics.id)

    @entity.save

    @character = Character.new(:EntityId => @entity.id)
    
    @character.save
    
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def index
        @available_skills_ids = EntitySkill.where(["EntityId = ?", params[:character_id]]).pluck(:SkillId)
        @user_skills = Skill.where(["Skills.Id IN (?, ?)", @available_skills_ids.first, @available_skills_ids.last])
        @available_skills = Skill.where(["Skills.Id NOT IN (?, ?)", @available_skills_ids.first, @available_skills_ids.last])
    end
    def show
        @skill = Skill.find(params[:id])
    end
    def create
        @params = params[:skill]
     
        params.permit!
        @skill = Skill.new(:Name => params[:skill][:name],
                            :Description => params[:skill][:description],
                            :ManaCost => params[:skill][:mana_cost],
                            :Damage => params[:skill][:damage],
                            :Multiplier => params[:skill][:multiplier])

        @skill.save                          
      end
    def update
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters/skills_helper.rb
module Characters::SkillsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/index.html.erb
<div class="container">
    <table class="table">
        <tr class="base-table-row">
            <th>Name</th>
            <th>Race</th>
            <th>Level</th>
        </tr>
        <% @characters.each do |character| %>
        <tr class="base-table-row row-clickable">
        
            <td><%= link_to character.Name, character_path(character) %></td>
            <td><%= character.race.Name %></td>
            <td><%= character.Level %></td>
        </tr>
        <% end %>
    </table>
    <a href="/characters/new" class="text-center">
        <div class="add-redirect">
            +
        </div>
    </a>
</div>

app/views/characters/new.html.erb
<div class="container d-flex justify-content-center">
    <div class="col-3 text-center">
        <%= form_with scope: :character, url: characters_path, local: true do |form| %>
            <p>
                <%= form.label :name %><br>
                <%= form.text_field :name %>
            </p>
            <p>
                <%= form.label :age %><br>
                <%= form.text_field :age %>
            </p>
            <p>
                <%= form.label :race %><br>
                <%= form.text_field :race %>
            </p>
            <p>
                <%= form.label :sex %><br>
                <%= form.text_field :sex %>
            </p>
            <p>
                <%= form.label :strength %><br>
                <%= form.text_field :strength %>
            </p>
            <p>
                <%= form.label :dexterity %><br>
                <%= form.text_field :dexterity %>
            </p>
            <p>
                <%= form.label :inteligence %><br>
                <%= form.text_field :inteligence %>
            </p>
            <p>
                <%= form.label :wisdom %><br>
                <%= form.text_field :wisdom %>
            </p>
            <p>
                <%= form.label :luck %><br>
                <%= form.text_field :luck %>
            </p>
            <p>
                <%= form.label :charisma %><br>
                <%= form.text_field :charisma %>
            </p>
            <p>
                <%= form.label :quote %><br>
                <%= form.text_field :quote %>
            </p>
            <p>
                <%= form.label :story %><br>
                <%= form.text_field :story %>
            </p>
            <p>
                <%= form.submit %>
            </p>
        <% end %>
    </div>
</div>

app/views/characters/show.html.erb
<div class="container">
    <div class="row">
        <div class="col">
            <div class="card border-secondary" style="margin:10px">
                <div class="card-body" style="height:300px">
                    <h4 class="card-title">Skills: </h4>
                    <% @character.skill.each do |skill| %>
                        <p class="card-text"><%= link_to skill.Name, character_skill_path(@character, skill) %></p>
                    <% end %>
                    <%= link_to '+', character_skills_path(@character) %>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card border-secondary" style="margin:10px;">
                <div class="card-body">
                    <div class="row">
                        <div class="col">
                            <h4 class="card-title"><%= @character.Name %></h4>
                            <p class="card-text"><%= @character.Age %> years</p>
                            <p class="card-text"><%= @character.Sex %></p>
                            <p class="card-text"><%= @character.Level %>th level</p>
                            <p class="card-text">Health: <%= @character.condition.Health %>/<%= @character.condition.MaxHealth %></p>
                            <p class="card-text">Mana: <%= @character.condition.Mana %>/<%= @character.condition.MaxMana %></p>
                            <p class="card-text">Experience: <%= @character.condition.Experience %>/<%= @character.condition.MaxExperience %></p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card border-secondary" style="margin:10px">
                <div class="card-body">
                    <h4 class="card-title">Contribution points: </h4>
                    <table class="table table-hover">
                        <tr class="table-default">
                            <th scope="row">Strength</th>
                            <td><%= @character.statistic.Strength %></td>
                        </tr>
                        <tr class="table-default">
                            <th scope="row">Dexterity</th>
                            <td><%= @character.statistic.Dexterity %></td>
                        </tr>
                        <tr class="table-default">
                            <th scope="row">Intelligence</th>
                            <td><%= @character.statistic.Inteligence %></td>
                        </tr>
                        <tr class="table-default">
                            <th scope="row">Wisdom</th>
                            <td><%= @character.statistic.Wisdom %></td>
                        </tr>
                        <tr class="table-default">
                            <th scope="row">Luck</th>
                            <td><%= @character.statistic.Luck %></td>
                        </tr>
                        <tr class="table-default">
                            <th scope="row">Charisma</th>
                            <td><%= @character.statistic.Charisma %></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card border-secondary" style="margin: 10px">
                <div class="card-body">
                    <blockquote class="blockquote">
                        <p class="mb-0 text-muted"><%= @character.Quote %></p>
                    </blockquote>
                    <blockquote class="blockquote">
                        <p class="mb-0"><%= @character.Story %></p>
                    </blockquote>
                </div>
            </div>
            <div class="card border-secondary" style="margin: 10px">
                <div class="card-body border-secondary">
                    <div class="card-title">
                        <h4> <%= @character.race.Name %> </h4>
                    </div>
                    <blockquote class="blockquote">
                        <p class="mb-0"><%= @character.race.BackStory %></p>
                    </blockquote>
                </div>
            </div>

        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rpg</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
    crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/skills/index.html.erb
<div class="container">
        <div class="col-md-4" style="float: left;" id="skills-available-container">
        <% @available_skills.each do |available_skill| %>
            <div id="<%= available_skill.Id %>" class="skill-row-available">
                <p><%= available_skill.Name %></p>
            </div>
        <% end %> 
    </div>
    <div class="col-md-4" style="float: left; text-align:center;"> 
        
        <button class="btn btn-primary" id="left-to-right-button"> > </button> 
        <br/>
        <br/>
        <button class="btn btn-primary" id="right-to-left-button"> < </button>
        <br><br><br>
        <div id="assign-form">
            <%= form_with scope: :skill, url: character_skill_path(params[:character_id], 1), method: :put, local: true do |form| %> 
                <input type="hidden" value="<%= params[:character_id] %>}}" name="character_id" id="character_id">
                <%= form.submit %>
            <% end %>
        </div>
        <%= link_to 'Add new skills', new_character_skill_path(params[:character_id]) %>

    </div>
    <div class="col-md-4" style="float: left;" id="skills-assigned-container">
        <% @user_skills.each do |user_skill| %>
            <div id="<%= user_skill.Id %>" class="skill-row-assigned">
                <p><%= user_skill.Name %></p>
            </div>
        <% end %> 
    </div>
</div>

<script type="text/javascript">
        $(document).ready(function()
        {
            $('.skill-row-available').click(function()
            {
                $(this).toggleClass("clicked");
            });
            $('.skill-row-assigned').click(function()
            {
                $(this).toggleClass("clicked");
            });

            $("#left-to-right-button").click(function()
            {
                var toAdd = $(".skill-row-available.clicked");
                console.log('To add: ' + toAdd);
                var skillsAssigned = $("#skills-assigned-container");
                console.log(skillsAssigned);

                toAdd.removeClass("skill-row-available").addClass("skill-row-assigned").removeClass("clicked");
                skillsAssigned.append(toAdd);
            });

            $("#right-to-left-button").click(function()
            {
                var toAdd = $(".skill-row-assigned.clicked");
                console.log('To add: ' + toAdd);
                var skillsAvailable = $("#skills-available-container");
                console.log(skillsAvailable);

                toAdd.removeClass("skill-row-assigned").addClass("skill-row-available").removeClass("clicked");
                skillsAvailable.append(toAdd);
            });
            $("#assign-form").on("submit", function()
            {
                var idsTable = [];
                $('.skill-row-assigned').each(function()
                {
                    var $this = $(this);
                    idsTable.push($this.attr('id'));
                });
                console.log(idsTable);
                $("<input />").attr("type", "hidden")
                .attr("name", "selected_skills")
                .attr("id", "selected_skills")
                .attr("value", JSON.stringify(idsTable))
                .appendTo("#assign-form");
                return true;
            })

        });
    </script>

app/views/skills/new.html.erb
<div class="container d-flex justify-content-center">
    <div class="col-3 text-center">
    <%= form_with scope: :skill, url: character_skills_path, local: true do |form| %>
        <p>
            <%= form.label :name %><br>
            <%= form.text_field :name %>
        </p>
        <p>
            <%= form.label :description %><br>
            <%= form.text_field :description %>
        </p>
        <p>
            <%= form.label :mana_cost %><br>
            <%= form.text_field :mana_cost %>
        </p>
        <p>
            <%= form.label :damage %><br>
            <%= form.text_field :damage %>
        </p>
        <p>
            <%= form.label :multiplier %><br>
            <%= form.text_field :multiplier %>
        </p>
        <p>
            <%= form.submit %>
        </p>
        <% end %>
    </div>
</div>

app/views/skills/show.html.erb
<div class="container justify-content-center">    
    <div class="col">
            <div class="card border-secondary" style="margin:10px">
                <div class="card-body" style="height:300px">
                    <h4 class="card-title"><%= @skill.Name %> </h4>
                    <p class="card-text">Damage: <%= @skill.Damage %> </p>
                    <p class="card-text">Mana cost: <%= @skill.ManaCost %> </p>
                    <p class="card-text">Multiplier: <%= @skill.Multiplier %> </p>
                    <p class="card-text">Description: <%= @skill.Description %></p>
                    <%= link_to 'GoBack', character_url(params[:character_id]) %>
                </div>
            </div>
                
    </div>   
</div>